string NAME="Sandshark Adapt Objective Message"

float64     prev_end_time
int32       prev_command_id
uint8       prev_coord_frame
int32       prev_command
float64     prev_param1
float64     prev_param2
float64     prev_param3
float64     prev_param4
float64     prev_param5
float64     prev_param6
float64     prev_param7
uint8       prev_auto_continue

float64     start_time
int32       command_id
int32       command_sub_id
uint8       coord_frame
int32       command
float64     param1
float64     param2
float64     param3
float64     param4
float64     param5
float64     param6
float64     param7
uint8       auto_continue

uint8       next_coord_frame
int32       next_command_id
int32       next_command
float64     next_param1
float64     next_param2
float64     next_param3
float64     next_param4
float64     next_param5
float64     next_param6
float64     next_param7
uint8       next_auto_continue
