string NAME="Sandshark Motion Corrected Message"

float64     timestamp

float64     accel_x
float64     accel_y
float64     accel_z
float64     linear_x
float64     linear_y
float64     linear_z
float64     gravity_x
float64     gravity_y
float64     gravity_z
uint8       accel_status

float64     mag_x
float64     mag_y
float64     mag_z
uint8       mag_status

float64     gyro_x
float64     gyro_y
float64     gyro_z
uint8       gyro_status

