string NAME="Sandshark Objective Command Message"

bool        start_mission
bool        stop_mission

bool        pop_objective
int32       pop_command_id
int32       pop_commands_sub_id
string      pop_reason

bool        push_objective
int32       push_command_id
int32       push_command
string      push_reason
uint8       coord_frame
uint16      command
float64     param1
float64     param2
float64     param3
float64     param4
float64     param5
float64     param6
float64     param7
uint8       auto_continue

