{correctTailconePerRoll: true, depthclipCmd: true, depthcmdMax: 0.5236, depthcmdMin: -0.5236,
 depthpgain: 0.3, depthigain: 0.2, depthdgain: 0.03, depthimax: 0.1,
 headingpgain: 0.5, headingigain: 0.01, headingdgain: 0.0,  headingimax: 0.2,
headingwrapAngles: true, pitchigain: 0.0, pitchimax: 0.5, pitchpgain: 0.35,
pitchwrapAngles: true, rpm_to_speed: 0.0008}
