/* THIS IS A HACK UNTIL CATKIN SWITCH COMPLETED, THEN REVISIT. */
/* MACRO SHOULD ALSO BE NAMED BLUEFIN_SANDSHARK_COMMON_VERSION OR SOMETHING. */

#ifndef _BLUEFIN__SANDSHARK__SANDSHARK_COMMON__VERSION_H_
#define _BLUEFIN__SANDSHARK__SANDSHARK_COMMON__VERSION_H_

#define VERSION "v1.0"

#endif
